export const dataList = [
  {
    Id: 1,
    name: '財團法人中華啟能基金會',
    phoneNumber: '(02)2671-3001轉2209',
    cityName: '新北市',
    url: 'https://www.spris.org.tw/',
  },
  {
    Id: 2,
    name: '財團法人中華民國唐氏症基金會',
    phoneNumber: '(02)2278-9321#246',
    cityName: '新北市',
    url: 'https://www.rocdown-syndrome.org.tw/',
  },
  {
    Id: 3,
    name: '新北市喜憨兒庇護工場',
    phoneNumber: '(02)8221-7676#111',
    cityName: '新北市',
    url: 'https://www.c-are-us.org.tw/',
  },
  {
    Id: 4,
    name: '財團法人台北市自閉兒社會福利基金會附設愛肯樂活工場',
    phoneNumber: '(02)2599-3803#18',
    cityName: '臺北市',
    url: 'https://www.fact.org.tw/',
  },
  {
    Id: 5,
    name: '社團法人中華善愛社福協會',
    phoneNumber: '(02)2966-2058',
    cityName: '新北市',
    url: 'https://sanlove.sino1.com.tw/',
  },
  {
    Id: 6,
    name: '財團法人天主教光仁社會福利基金會附設臺北市私立育仁啟能中心',
    phoneNumber: '(02)2382-1090#12',
    cityName: '臺北市',
    url: 'https://www.kjswf.org.tw/',
  },
  {
    Id: 7,
    name: '財團法人臺北市小愉兒社會福利基金會',
    phoneNumber: '(02)2422-0310',
    cityName: '基隆市',
    url: 'https://i-happ-link.org.tw/',
  },
  {
    Id: 8,
    name: '財團法人育成社會福利基金會事業部',
    phoneNumber: '(02)2705-2588#27',
    cityName: '臺北市',
    url: 'https://www.ycswf.org.tw/',
  },
  {
    Id: 9,
    name: '糕菲庇護工廠',
    phoneNumber: '(02)2785-2499轉9',
    cityName: '臺北市',
    url: 'https://gofe.com.tw/',
  },
  {
    Id: 10,
    name: '社團法人基隆市聾啞福利協進會附設勵聲美饕',
    phoneNumber: '(02)2429-1433',
    cityName: '基隆市',
    url: 'https://www.facebook.com/groups/391870854203778/',
  },
  {
    Id: 11,
    name: '財團法人伊甸社會福利基金會附設伊甸烘焙咖啡屋',
    phoneNumber: '(03)4278229轉101',
    cityName: '桃園市',
    url: 'https://edenmall.eden.org.tw/',
  },
  {
    Id: 12,
    name: '財團法人桃園市私立觀音愛心家園',
    phoneNumber: '(03)483-3820',
    cityName: '桃園市',
    url: 'https://www.kindgarden.org.tw/',
  },
  {
    Id: 13,
    name: '財團法人桃園市私立路得啟智學園',
    phoneNumber: '(03)498-0096#115',
    cityName: '桃園市',
    url: 'https://ruth.eoffering.org.tw/',
  },
  {
    Id: 14,
    name: '財團法人桃園市私立心燈啟智教養院',
    phoneNumber: '(03)420-5558#116',
    cityName: '桃園市',
    url: 'https://shin-deng.org/',
  },
  {
    Id: 15,
    name: '衛生福利部桃園療養院附設樂桃桃咖啡簡餐坊',
    phoneNumber: '(03)369-8553#2633',
    cityName: '桃園市',
    url: 'https://www.typc.mohw.gov.tw/',
  },
  {
    Id: 16,
    name: '財團法人台灣省私立香園紀念教養院',
    phoneNumber: '(03)5690951轉118',
    cityName: '新竹縣',
    url: 'https://www.hsiangyuan.org.tw/',
  },
  {
    Id: 17,
    name: '幼安歡喜兒咖啡屋',
    phoneNumber: '(03)733-8180',
    cityName: '苗栗縣',
    url: 'https://www.yuan.org.tw/',
  },
  {
    Id: 18,
    name: '財團法人瑪利亞社會福利基金會',
    phoneNumber: '04-2471-3535轉1403',
    cityName: '臺中市',
    url: 'https://www.maria.org.tw/',
  },
  {
    Id: 19,
    name: '財團法人臺中市私立十方社會福利慈善事業基金會附設社會企業發展部',
    phoneNumber: '(04)2239-3008',
    cityName: '臺中市',
    url: 'https://www.sfang.org.tw/',
  },
  {
    Id: 20,
    name: '社團法人臺中市身心障礙者福利關懷協會附設微笑天使烘焙坊',
    phoneNumber: '(04)22607321#30',
    cityName: '臺中市',
    url: 'https://www.facebook.com/siangsinbread/?locale=zh_TW',
  },
  {
    Id: 21,
    name: '立達啟能訓練中心附設實習商店',
    phoneNumber: '(04)2202-8888#121',
    cityName: '臺中市',
    url: 'https://www.saint-coletta.org.tw/OnePage.aspx?tid=114',
  },
  {
    Id: 22,
    name: '社團法人臺中市蓮心自強服務協會',
    phoneNumber: '(04)2680-5843',
    cityName: '臺中市',
    url: 'https://www.lotusheart.org.tw/index_tw.php',
  },
  {
    Id: 23,
    name: '財團法人彰化縣私立慈生仁愛院',
    phoneNumber: '(04)722-2735#111',
    cityName: '彰化縣',
    url: 'https://www.cisheng.org.tw/',
  },
  {
    Id: 24,
    name: '財團法人彰化縣私立基督教喜樂保育院',
    phoneNumber: '(04)890-3281',
    cityName: '彰化縣',
    url: 'https://www.joyce929.org.tw/',
  },
  {
    Id: 25,
    name: '社團法人彰化縣自閉症肯納家長協會附設肯納兒烘焙坊',
    phoneNumber: '(04)722-3460',
    cityName: '彰化縣',
    url: 'https://www.ckbakery.com.tw/h/index?key=rxch9&srsltid=AfmBOora9ixhY1outUBLZfO8PAU5kQXE9aYAxkWZ_BUgEFKQbq1v4719',
  },
  {
    Id: 26,
    name: '社團法人雲林縣聲暉協進會',
    phoneNumber: '(05)597-4861',
    cityName: '雲林縣',
    url: 'https://yunlinsound.webnode.tw/%e7%94%a2%e5%93%81dm/',
  },
  {
    Id: 27,
    name: '財團法人若竹兒教育基金會附設嘉義縣私立若竹兒智能發展中心',
    phoneNumber: '(05)220-9987',
    cityName: '嘉義縣',
    url: 'https://www.roc.org.tw/',
  },
  {
    Id: 28,
    name: '戴德森醫療財團法人嘉義基督教醫院附設再耕園咖啡庇護工場',
    phoneNumber: '(05)285-2698#232',
    cityName: '嘉義市',
    url: 'https://www.cych.org.tw/',
  },
  {
    Id: 29,
    name: '財團法人台南市私立天主教瑞復益智中心附設漁光小舖',
    phoneNumber: '(06)391-1531轉252',
    cityName: '臺南市',
    url: 'https://www.raphael.org.tw/',
  },
  {
    Id: 30,
    name: '衛生福利部嘉南療養院愛的集團',
    phoneNumber: '(06)279-5019轉1227',
    cityName: '臺南市',
    url: 'https://www.cnpc.mohw.gov.tw/',
  },
  {
    Id: 31,
    name: '財團法人台灣省私立鴻佳啟能庇護中心',
    phoneNumber: '(06)262-3456#109',
    cityName: '臺南市',
    url: 'https://hc.eoffering.org.tw/',
  },
  {
    Id: 32,
    name: '社團法人臺南市心智障礙關顧協會附設展翼烘焙坊',
    phoneNumber: '(06)201-3217、(06)201-4060',
    cityName: '臺南市',
    url: 'https://zhanyi.flyangel.org.tw/',
  },
  {
    Id: 33,
    name: '財團法人台南市私立蓮心園社會福利慈善事業基金會',
    phoneNumber: '(06)688-2711分機609',
    cityName: '臺南市',
    url: 'https://www.lsy.org.tw/',
  },
  {
    Id: 34,
    name: '高雄市立凱旋醫院附設社區復健中心夢想起飛商行',
    phoneNumber: '(07)713-1236#235',
    cityName: '高雄市',
    url: 'https://ksph.kcg.gov.tw/',
  },
  {
    Id: 35,
    name: '中外餅舖有限公司附設中外餅舖庇護工場',
    phoneNumber: '07-5886366',
    cityName: '高雄市',
    url: 'https://www.chinese-cake.com/',
  },
  {
    Id: 36,
    name: '社團法人高雄市小草關懷協會',
    phoneNumber: '(07)806-1733',
    cityName: '高雄市',
    url: 'https://grasscare.org.tw/',
  },
  {
    Id: 37,
    name: '社團法人高雄市心理復健協會',
    phoneNumber: '(07)338-1771',
    cityName: '高雄市',
    url: 'http://www.cilifuza.org.tw/',
  },
  {
    Id: 38,
    name: '一家工場',
    phoneNumber: '(07)790-2239',
    cityName: '高雄市',
    url: 'https://www.syinlu.org.tw/about/service_location/23',
  },
  {
    Id: 39,
    name: '社團法人高雄三山脊損重建協會',
    phoneNumber: '(07)719-1039',
    cityName: '高雄市',
    url: 'https://www.facebook.com/groups/409493713517101/',
  },
  {
    Id: 40,
    name: '長庚醫療財團法人高雄長庚紀念醫院附設湖畔咖啡屋',
    phoneNumber: '(07)731-7123#8769',
    cityName: '高雄市',
    url: 'https://www.cgmh.org.tw/',
  },
  {
    Id: 41,
    name: '社團法人屏東縣向陽啟能協會',
    phoneNumber: '(08)721-7361',
    cityName: '屏東縣',
    url: 'https://www.facebook.com/tosun7217361/',
  },
  {
    Id: 42,
    name: '財團法人屏東基督教勝利之家附設膳工坊庇護工場',
    phoneNumber: '(08)736-6294#226',
    cityName: '屏東縣',
    url: 'https://www.vhome.org.tw/',
  },
  {
    Id: 43,
    name: '慢慢恆春烘焙坊 (原：藍色海遇琪拉烘焙坊）',
    phoneNumber: '0927-558-828',
    cityName: '屏東縣',
    url: 'https://www.instagram.com/slowly_angel/',
  },
  {
    Id: 44,
    name: '財團法人蘭智社會福利基金會',
    phoneNumber: '(03)961-0137#25(基金會)、(03)953-0129(烘培坊)',
    cityName: '宜蘭縣',
    url: 'https://lan-chui.org.tw/',
  },
  {
    Id: 45,
    name: '財團法人宜蘭縣私立蘭馨婦幼中心',
    phoneNumber: '(03)951-0518#225',
    cityName: '宜蘭縣',
    url: 'https://www.roton.tw/ap/index.aspx',
  },
  {
    Id: 46,
    name: '臺北榮民總醫院員山分院附設庇護工場',
    phoneNumber: '(03)923-3791',
    cityName: '宜蘭縣',
    url: 'https://www.ysvh.gov.tw/',
  },
  {
    Id: 47,
    name: '財團法人台灣基督教門諾會附設花蓮縣黎明身心障礙者庇護工場',
    phoneNumber: '(03)846-0527',
    cityName: '花蓮縣',
    url: 'https://www.newdawn.org.tw/',
  },
  {
    Id: 48,
    name: '財團法人台東縣私立牧心智能發展中心附設庇護性烘焙工場',
    phoneNumber: '(089)237-121#160',
    cityName: '臺東縣',
    url: 'https://www.musoon.org.tw/',
  },
  {
    Id: 49,
    name: '社團法人澎湖縣慢飛天使服務協會',
    phoneNumber: '(06)926-9855',
    cityName: '澎湖縣',
    url: 'https://www.phchildrencare.artcom.tw/ap/index.aspx',
  },
  {
    Id: 50,
    name: '財團法人晨光社會福利基金會附設妙妙屋庇護工場',
    phoneNumber: '(082)331345',
    cityName: '金門縣',
    url: 'https://www.facebook.com/people/%E5%A6%99%E5%A6%99%E5%B1%8B%E5%BA%87%E8%AD%B7%E5%B7%A5%E5%A0%B4/100063773088691/?ref=embed_page',
  },
  {
    Id: 51,
    name: '更生少年關懷協會',
    phoneNumber: '(02)22977113',
    cityName: '新北市',
    url: 'https://www.616.org.tw/',
  },
  {
    Id: 52,
    name: '失親兒福利基金會',
    phoneNumber: '(02)27477555',
    cityName: '臺北市',
    url: 'https://www.orphan.org.tw/',
  },
  {
    Id: 53,
    name: '菩提澄園庇護工場',
    phoneNumber: '(06)5712342',
    cityName: '臺南市',
    url: 'https://joo.tw/puti/',
  },
  {
    Id: 54,
    name: '社團法人台灣福氣社區關懷協會',
    phoneNumber: '(04)26268178',
    cityName: '臺中市',
    url: 'https://www.fortune0619.com.tw/portal/',
  },
  {
    Id: 55,
    name: '財團法人臺中市私立信望愛智能發展中心',
    phoneNumber: '(04)25355030',
    cityName: '臺中市',
    url: 'https://www.fhl.org.tw/',
  },
  {
    Id: 56,
    name: '社團法人台灣技職教育產學研合作發展協會',
    phoneNumber: '(04)26805153',
    cityName: '臺中市',
    url: 'https://www.facebook.com/taiwanvea/?locale=zh_TW',
  },
  {
    Id: 57,
    name: '社團法人屏東縣自閉症協進會',
    phoneNumber: '(08)7351024',
    cityName: '屏東縣',
    url: 'https://www.facebook.com/autismpt/?locale=zh_TW',
  },
  {
    Id: 58,
    name: '財團法人伊甸社會福利基金會-創皂工坊',
    phoneNumber: '(08)8711612',
    cityName: '屏東縣',
    url: 'https://www.eden.org.tw/',
  },
  {
    Id: 59,
    name: '社團法人屏東縣啟智協進會',
    phoneNumber: '(08)7383015、(08)7750688',
    cityName: '屏東縣',
    url: 'https://pamr.org.tw/',
  },
  {
    Id: 60,
    name: '財團法人屏東縣私立基督教伯大尼之家',
    phoneNumber: '(08)7367264',
    cityName: '屏東縣',
    url: 'https://www.bethany-pt.org/',
  },
  {
    Id: 61,
    name: '社團法人屏東縣向陽康復之友協會附設誠欣工作坊',
    phoneNumber: '(08)7551200',
    cityName: '屏東縣',
    url: 'https://www.facebook.com/p/%E8%AA%A0%E6%AC%A3%E5%B7%A5%E4%BD%9C%E5%9D%8A-61564214742865/',
  },
  {
    Id: 62,
    name: '社團法人屏東縣微笑關懷協會',
    phoneNumber: '(08)7325100',
    cityName: '屏東縣',
    url: 'https://www.facebook.com/smileca1015/?locale=zh_TW',
  },
];
